theme: jekyll-theme-minimal

![Alt text for your image](/path/to/your/image.jpg)
*A brief caption for the image*

## Introduction
Here is a paragraph introducing yourself. You can write about your background, interests, or any other information you'd like to share.

## Research Projects

### Project 1 Title
Brief description of Project 1. You can add more details, links, or even images.

### Project 2 Title
Brief description of Project 2.

### Project 3 Title
Brief description of Project 3.

## Course Projects

### Course Project 1
Brief description of Course Project 1.

### Course Project 2
Brief description of Course Project 2.
