remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Kejing Yan]

logo: https://github.com/anyfruit/anyfruit.github.io/blob/main/8cf26e9a971119d5ec56bcbd5102ed8.jpg?raw=true

description: Hello! Welcome to my personal webpage where I share insights into my research in machine learning and data science, along with my academic projects and collaborations.
